name: Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # 主要平台构建测试
          - goos: windows
            goarch: amd64
            output: mikomail-windows-amd64.exe
          - goos: linux
            goarch: amd64
            output: mikomail-linux-amd64
          - goos: darwin
            goarch: amd64
            output: mikomail-darwin-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
        # 排除工具目录，只构建主程序
        go build -ldflags="-s -w" -o ${{ matrix.output }} ./main.go

        # 验证构建结果
        if [ "${{ matrix.goos }}" = "linux" ]; then
          file ${{ matrix.output }}
          chmod +x ${{ matrix.output }}
        fi

    - name: Create release package
      run: |
        # 创建发布目录
        RELEASE_DIR="miko-email-${{ matrix.goos }}-${{ matrix.goarch }}"
        mkdir -p "$RELEASE_DIR"

        # 复制二进制文件
        cp ${{ matrix.output }} "$RELEASE_DIR/"

        # 复制必要的文件和目录
        cp config.yaml "$RELEASE_DIR/"
        cp -r web "$RELEASE_DIR/"
        cp -r tools "$RELEASE_DIR/"

        # 创建必要的目录
        mkdir -p "$RELEASE_DIR/dkim_keys"
        mkdir -p "$RELEASE_DIR/logs"
        mkdir -p "$RELEASE_DIR/data"

        # 复制文档文件
        cp README.md "$RELEASE_DIR/" 2>/dev/null || echo "README.md not found, skipping"
        cp "部署指南.txt" "$RELEASE_DIR/" 2>/dev/null || echo "部署指南.txt not found, skipping"
        cp "开发指南.txt" "$RELEASE_DIR/" 2>/dev/null || echo "开发指南.txt not found, skipping"
        cp "故障排除.txt" "$RELEASE_DIR/" 2>/dev/null || echo "故障排除.txt not found, skipping"

        # 创建压缩包
        if [ "${{ matrix.goos }}" = "windows" ]; then
          # Windows 使用 zip
          zip -r "${RELEASE_DIR}.zip" "$RELEASE_DIR"
          echo "PACKAGE_FILE=${RELEASE_DIR}.zip" >> $GITHUB_ENV
        else
          # Linux/macOS 使用 tar.gz
          tar -czf "${RELEASE_DIR}.tar.gz" "$RELEASE_DIR"
          echo "PACKAGE_FILE=${RELEASE_DIR}.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: miko-email-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ${{ env.PACKAGE_FILE }}
        retention-days: 7
